"use client";

import { Info } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/utils";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface FinancialInfoProps {
  listing: {
    askingPrice: number | string;
    annualRevenue?: number | string | null;
    cashFlowSDE?: number | string | null;
    netIncome?: number | string | null;
    profitMargin?: number | string | null;
    askingMultiple?: number | string | null;
    monthlyRent?: number | string | null;
    rentEscalation?: string | null;
    annualPayroll?: number | string | null;
    totalExpenses?: number | string | null;
    inventoryValue?: number | string | null;
    inventoryIncluded?: boolean | null;
    ffeValue?: number | string | null;
    ffeIncluded?: boolean | null;
    sellerFinancing: boolean;
    sbaFinancingAvailable: boolean;
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toNumber(value: number | string | null | undefined): number | null {
  if (value == null) return null;
  const n = typeof value === "string" ? parseFloat(value) : value;
  return Number.isFinite(n) ? n : null;
}

// ---------------------------------------------------------------------------
// Tooltip definitions — plain-English explanations for every financial field
// ---------------------------------------------------------------------------

const TOOLTIPS: Record<string, string> = {
  askingPrice:
    "The total price the seller is asking for the business, including tangible and intangible assets.",
  annualRevenue:
    "Gross revenue generated by the business over the most recent 12-month period, before any expenses are deducted.",
  cashFlowSDE:
    "Seller's Discretionary Earnings — total financial benefit to a single owner-operator, including salary, perks, and non-cash expenses added back.",
  netIncome:
    "The business's profit after all operating expenses, taxes, and interest have been deducted from revenue.",
  profitMargin:
    "Net income as a percentage of annual revenue. A higher margin indicates greater profitability.",
  askingMultiple:
    "Asking price divided by annual cash flow (SDE). Lower multiples may indicate better value relative to earnings.",
  monthlyRent:
    "The monthly lease payment for the business premises. Important for understanding fixed overhead costs.",
  rentEscalation:
    "How rent increases over time — typically expressed as a percentage per year or a fixed dollar amount.",
  annualPayroll:
    "Total yearly cost of employee wages, salaries, and related benefits (excluding owner compensation).",
  totalExpenses:
    "All annual operating expenses combined, including rent, payroll, supplies, and other overhead.",
  inventoryValue:
    "The estimated value of physical inventory (products, materials, supplies) at the time of sale.",
  ffeValue:
    "Furniture, Fixtures & Equipment — the value of physical assets such as tables, shelving, kitchen equipment, and machinery.",
  sellerFinancing:
    "When the seller agrees to finance part of the purchase price, allowing the buyer to pay over time instead of all at closing.",
  sbaFinancingAvailable:
    "The business qualifies for an SBA (Small Business Administration) loan, which offers favorable interest rates and longer repayment terms.",
};

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function InfoTooltip({ text }: { text: string }) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <button
          type="button"
          className="inline-flex items-center justify-center rounded-full text-muted-foreground/60 hover:text-muted-foreground transition-colors duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          aria-label="More information"
        >
          <Info className="h-3.5 w-3.5" strokeWidth={2} />
        </button>
      </TooltipTrigger>
      <TooltipContent side="top" sideOffset={6} className="max-w-64 text-pretty">
        {text}
      </TooltipContent>
    </Tooltip>
  );
}

interface RowProps {
  label: string;
  tooltip: string;
  value: React.ReactNode;
  even: boolean;
}

function Row({ label, tooltip, value, even }: RowProps) {
  return (
    <div
      className={`flex items-center justify-between gap-4 px-4 py-3 ${
        even ? "bg-muted/40" : ""
      }`}
    >
      <div className="flex items-center gap-2 min-w-0">
        <span className="text-sm font-medium text-foreground/80 whitespace-nowrap">
          {label}
        </span>
        <InfoTooltip text={tooltip} />
      </div>
      <div className="text-sm font-semibold text-foreground text-right shrink-0">
        {value}
      </div>
    </div>
  );
}

function NotDisclosed() {
  return (
    <span className="text-muted-foreground/60 font-normal italic">
      Not disclosed
    </span>
  );
}

function AvailableBadge({ available }: { available: boolean }) {
  if (available) {
    return (
      <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-400 dark:border-emerald-800 font-medium">
        Available
      </Badge>
    );
  }
  return (
    <Badge
      variant="secondary"
      className="bg-muted text-muted-foreground border-border font-medium"
    >
      Not available
    </Badge>
  );
}

function IncludedBadge({ included }: { included: boolean | null | undefined }) {
  if (included == null) return null;
  if (included) {
    return (
      <Badge className="bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-400 dark:border-emerald-800 font-medium text-[11px]">
        Included
      </Badge>
    );
  }
  return (
    <Badge
      variant="secondary"
      className="bg-muted text-muted-foreground border-border font-medium text-[11px]"
    >
      Not included
    </Badge>
  );
}

// ---------------------------------------------------------------------------
// Main Component
// ---------------------------------------------------------------------------

export function FinancialInfo({ listing }: FinancialInfoProps) {
  const askingPrice = toNumber(listing.askingPrice);
  const annualRevenue = toNumber(listing.annualRevenue);
  const cashFlowSDE = toNumber(listing.cashFlowSDE);
  const netIncome = toNumber(listing.netIncome);
  const profitMargin = toNumber(listing.profitMargin);
  const askingMultiple = toNumber(listing.askingMultiple);
  const monthlyRent = toNumber(listing.monthlyRent);
  const annualPayroll = toNumber(listing.annualPayroll);
  const totalExpenses = toNumber(listing.totalExpenses);
  const inventoryValue = toNumber(listing.inventoryValue);
  const ffeValue = toNumber(listing.ffeValue);

  // Build rows — each entry: [label, tooltipKey, rendered value]
  const rows: [string, string, React.ReactNode][] = [
    [
      "Asking Price",
      "askingPrice",
      askingPrice != null ? formatCurrency(askingPrice) : <NotDisclosed />,
    ],
    [
      "Annual Revenue",
      "annualRevenue",
      annualRevenue != null ? formatCurrency(annualRevenue) : <NotDisclosed />,
    ],
    [
      "Cash Flow (SDE)",
      "cashFlowSDE",
      cashFlowSDE != null ? formatCurrency(cashFlowSDE) : <NotDisclosed />,
    ],
    [
      "Net Income",
      "netIncome",
      netIncome != null ? formatCurrency(netIncome) : <NotDisclosed />,
    ],
    [
      "Profit Margin",
      "profitMargin",
      profitMargin != null ? (
        `${Number(profitMargin.toFixed(1))}%`
      ) : (
        <NotDisclosed />
      ),
    ],
    [
      "Asking Multiple",
      "askingMultiple",
      askingMultiple != null ? (
        `${Number(askingMultiple.toFixed(1))}x`
      ) : (
        <NotDisclosed />
      ),
    ],
    [
      "Monthly Rent",
      "monthlyRent",
      monthlyRent != null ? formatCurrency(monthlyRent) : <NotDisclosed />,
    ],
    [
      "Rent Escalation",
      "rentEscalation",
      listing.rentEscalation ?? <NotDisclosed />,
    ],
    [
      "Annual Payroll",
      "annualPayroll",
      annualPayroll != null ? formatCurrency(annualPayroll) : <NotDisclosed />,
    ],
    [
      "Total Expenses",
      "totalExpenses",
      totalExpenses != null ? formatCurrency(totalExpenses) : <NotDisclosed />,
    ],
    [
      "Inventory",
      "inventoryValue",
      inventoryValue != null ? (
        <span className="inline-flex items-center gap-2">
          {formatCurrency(inventoryValue)}
          <IncludedBadge included={listing.inventoryIncluded} />
        </span>
      ) : (
        <NotDisclosed />
      ),
    ],
    [
      "FF&E",
      "ffeValue",
      ffeValue != null ? (
        <span className="inline-flex items-center gap-2">
          {formatCurrency(ffeValue)}
          <IncludedBadge included={listing.ffeIncluded} />
        </span>
      ) : (
        <NotDisclosed />
      ),
    ],
    [
      "Seller Financing",
      "sellerFinancing",
      <AvailableBadge key="sf" available={listing.sellerFinancing} />,
    ],
    [
      "SBA Financing",
      "sbaFinancingAvailable",
      <AvailableBadge key="sba" available={listing.sbaFinancingAvailable} />,
    ],
  ];

  return (
    <TooltipProvider delayDuration={200}>
      <Card className="overflow-hidden">
        <CardHeader className="border-b pb-4">
          <CardTitle className="text-lg font-semibold tracking-tight">
            Financial Information
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="divide-y divide-border/50">
            {rows.map(([label, tooltipKey, value], index) => (
              <Row
                key={tooltipKey}
                label={label}
                tooltip={TOOLTIPS[tooltipKey]}
                value={value}
                even={index % 2 === 0}
              />
            ))}
          </div>
        </CardContent>
      </Card>
    </TooltipProvider>
  );
}
