import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";
import bcrypt from "bcryptjs";

const adapter = new PrismaNeon({
  connectionString: process.env.DATABASE_URL!,
});
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding database...");

  // Create users
  const adminPassword = await bcrypt.hash("Admin123!", 12);
  const userPassword = await bcrypt.hash("User1234!", 12);

  const admin = await prisma.user.upsert({
    where: { email: "admin@mercatolist.com" },
    update: {},
    create: {
      email: "admin@mercatolist.com",
      name: "Admin User",
      hashedPassword: adminPassword,
      role: "ADMIN",
      emailVerified: new Date(),
    },
  });

  const broker1 = await prisma.user.upsert({
    where: { email: "sarah.broker@example.com" },
    update: {},
    create: {
      email: "sarah.broker@example.com",
      name: "Sarah Chen",
      displayName: "Sarah Chen",
      hashedPassword: userPassword,
      role: "BROKER",
      emailVerified: new Date(),
      brokerageName: "NYC Business Brokers",
      brokerageWebsite: "https://nycbusinessbrokers.example.com",
      brokeragePhone: "(212) 555-0100",
      bio: "Top-rated business broker specializing in restaurant and retail transactions across Manhattan and Brooklyn.",
    },
  });

  const broker2 = await prisma.user.upsert({
    where: { email: "mike.broker@example.com" },
    update: {},
    create: {
      email: "mike.broker@example.com",
      name: "Michael Torres",
      displayName: "Mike Torres",
      hashedPassword: userPassword,
      role: "BROKER",
      emailVerified: new Date(),
      brokerageName: "Empire State Business Sales",
      brokeragePhone: "(718) 555-0200",
      bio: "15+ years helping business owners in Queens and the Bronx find the right buyers.",
    },
  });

  const seller1 = await prisma.user.upsert({
    where: { email: "joe.seller@example.com" },
    update: {},
    create: {
      email: "joe.seller@example.com",
      name: "Joe Martino",
      hashedPassword: userPassword,
      role: "USER",
      emailVerified: new Date(),
      ownedBusiness: "Joe's Pizza — Astoria",
    },
  });

  const seller2 = await prisma.user.upsert({
    where: { email: "lisa.seller@example.com" },
    update: {},
    create: {
      email: "lisa.seller@example.com",
      name: "Lisa Park",
      hashedPassword: userPassword,
      role: "USER",
      emailVerified: new Date(),
    },
  });

  const buyer1 = await prisma.user.upsert({
    where: { email: "david.buyer@example.com" },
    update: {},
    create: {
      email: "david.buyer@example.com",
      name: "David Kim",
      hashedPassword: userPassword,
      role: "USER",
      emailVerified: new Date(),
      buyBox: {
        categories: ["Restaurants", "Cafes & Coffee Shops"],
        priceRange: { min: 200000, max: 800000 },
        boroughs: ["MANHATTAN", "BROOKLYN"],
      },
    },
  });

  console.log("Users created.");

  // Create listings
  const listings = [
    {
      slug: "joes-pizza-astoria",
      title: "Joe's Pizza — Astoria",
      description:
        "Well-established pizzeria in the heart of Astoria with a loyal customer base spanning 16+ years. Known for its authentic New York-style pizza, this turnkey operation features a fully equipped commercial kitchen, seating for 40, and a prime corner location with excellent foot traffic. The business has consistently generated strong revenue with healthy margins. All equipment in excellent condition, and the current staff is willing to stay on.",
      category: "Restaurants",
      askingPrice: 450000,
      annualRevenue: 850000,
      cashFlowSDE: 180000,
      netIncome: 145000,
      monthlyRent: 6500,
      yearEstablished: 2008,
      numberOfEmployees: 8,
      employeesWillingToStay: true,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 50,
      squareFootage: 1800,
      leaseTerms: "7 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Retirement",
      trainingSupport: "30 days of training included",
      address: "31-12 Broadway, Astoria, NY 11106",
      neighborhood: "Astoria",
      borough: "QUEENS" as const,
      zipCode: "11106",
      latitude: 40.7628,
      longitude: -73.9229,
      listedById: seller1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "brooklyn-heights-laundromat",
      title: "Brooklyn Heights Laundromat",
      description:
        "Semi-absentee coin laundromat in a high-density residential area of Brooklyn Heights. Fully automated operations with 30 washers and 25 dryers, all commercial grade. Minimal staffing required — one attendant during operating hours. Consistent revenue with low overhead. Recently renovated with modern machines and a clean, bright interior. Ideal for an investor looking for passive income.",
      category: "Laundromats & Dry Cleaners",
      askingPrice: 275000,
      annualRevenue: 380000,
      cashFlowSDE: 120000,
      netIncome: 95000,
      monthlyRent: 4200,
      yearEstablished: 2015,
      numberOfEmployees: 2,
      ownerInvolvement: "ABSENTEE" as const,
      ownerHoursPerWeek: 5,
      squareFootage: 2200,
      leaseTerms: "5 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Relocating out of state",
      address: "85 Montague St, Brooklyn, NY 11201",
      neighborhood: "Brooklyn Heights",
      borough: "BROOKLYN" as const,
      zipCode: "11201",
      latitude: 40.6935,
      longitude: -73.9962,
      listedById: broker1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "soho-boutique-fashion",
      title: "SoHo Boutique Fashion Store",
      description:
        "Premium fashion boutique on a prime SoHo street with exceptional foot traffic. Curated selection of independent and emerging designers. Strong brand identity with an active social media following of 25K+. Beautiful interior with custom fixtures. The business has built strong relationships with designers and a loyal clientele. Includes all inventory and fixtures.",
      category: "Clothing & Fashion",
      askingPrice: 1200000,
      annualRevenue: 1800000,
      cashFlowSDE: 350000,
      netIncome: 280000,
      monthlyRent: 18000,
      yearEstablished: 2012,
      numberOfEmployees: 6,
      employeesWillingToStay: true,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 45,
      squareFootage: 1500,
      leaseTerms: "4 years remaining",
      reasonForSelling: "Pursuing other ventures",
      inventoryValue: 150000,
      inventoryIncluded: true,
      address: "123 Spring St, New York, NY 10012",
      neighborhood: "SoHo",
      borough: "MANHATTAN" as const,
      zipCode: "10012",
      latitude: 40.7224,
      longitude: -73.9976,
      listedById: broker1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "fordham-barbershop",
      title: "Fordham Road Barbershop",
      description:
        "Busy barbershop on Fordham Road with steady walk-in traffic. 5 chairs, fully equipped. Established reputation in the neighborhood with a mix of regular customers and walk-ins. Simple business model with low overhead. Great opportunity for an owner-operator barber.",
      category: "Salons & Barbershops",
      askingPrice: 150000,
      annualRevenue: 220000,
      cashFlowSDE: 85000,
      monthlyRent: 2800,
      yearEstablished: 2019,
      numberOfEmployees: 3,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 40,
      squareFootage: 900,
      leaseTerms: "6 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Health reasons",
      address: "2450 Grand Concourse, Bronx, NY 10458",
      neighborhood: "Fordham",
      borough: "BRONX" as const,
      zipCode: "10458",
      latitude: 40.8607,
      longitude: -73.8985,
      listedById: seller2.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "williamsburg-coffee-shop",
      title: "Williamsburg Specialty Coffee",
      description:
        "Trendy specialty coffee shop in Williamsburg with a loyal following. Known for expertly crafted pour-overs, espresso drinks, and house-made pastries. Beautifully designed interior with exposed brick and custom woodwork. Active Instagram presence with 12K followers. Includes all equipment, recipes, and supplier relationships.",
      category: "Cafes & Coffee Shops",
      askingPrice: 350000,
      annualRevenue: 520000,
      cashFlowSDE: 130000,
      netIncome: 105000,
      monthlyRent: 5500,
      yearEstablished: 2017,
      numberOfEmployees: 7,
      employeesWillingToStay: true,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 35,
      squareFootage: 1100,
      leaseTerms: "8 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Opening a new concept elsewhere",
      trainingSupport: "2 weeks of training included",
      address: "205 Bedford Ave, Brooklyn, NY 11211",
      neighborhood: "Williamsburg",
      borough: "BROOKLYN" as const,
      zipCode: "11211",
      latitude: 40.7142,
      longitude: -73.9614,
      listedById: seller1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "jackson-heights-grocery",
      title: "Jackson Heights Grocery & Deli",
      description:
        "High-volume grocery and deli in the diverse Jackson Heights neighborhood. Strong mix of grocery, prepared foods, and deli counter sales. Located on a busy commercial strip with excellent visibility. Includes deli equipment, walk-in cooler, and all fixtures. Long-standing supplier relationships in place.",
      category: "Delis & Grocery Stores",
      askingPrice: 500000,
      annualRevenue: 1100000,
      cashFlowSDE: 200000,
      netIncome: 160000,
      monthlyRent: 7000,
      yearEstablished: 2005,
      numberOfEmployees: 10,
      employeesWillingToStay: true,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 55,
      squareFootage: 2500,
      leaseTerms: "10 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Retirement",
      inventoryValue: 45000,
      inventoryIncluded: true,
      address: "75-10 Roosevelt Ave, Jackson Heights, NY 11372",
      neighborhood: "Jackson Heights",
      borough: "QUEENS" as const,
      zipCode: "11372",
      latitude: 40.7499,
      longitude: -73.8831,
      listedById: broker2.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "midtown-nail-salon",
      title: "Midtown Nail Salon & Spa",
      description:
        "Upscale nail salon and spa in a prime Midtown East location near major office buildings. 10 manicure stations, 6 pedicure thrones, and 2 private treatment rooms. Strong weekday clientele from nearby offices. Premium service menu with high average ticket. Fully renovated in 2022.",
      category: "Nail Salons",
      askingPrice: 380000,
      annualRevenue: 620000,
      cashFlowSDE: 155000,
      monthlyRent: 8500,
      yearEstablished: 2018,
      numberOfEmployees: 12,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 40,
      squareFootage: 1400,
      leaseTerms: "6 years remaining",
      address: "350 Lexington Ave, New York, NY 10016",
      neighborhood: "Midtown East",
      borough: "MANHATTAN" as const,
      zipCode: "10016",
      latitude: 40.7502,
      longitude: -73.9759,
      listedById: broker1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "chelsea-gym-fitness",
      title: "Chelsea Boutique Fitness Studio",
      description:
        "Popular boutique fitness studio in Chelsea offering HIIT, yoga, and cycling classes. 3,000 sq ft space with top-of-the-line equipment. Active membership base of 400+ members. Strong brand with online booking system and app integration. Includes all equipment and active memberships.",
      category: "Gyms & Fitness Studios",
      askingPrice: 650000,
      annualRevenue: 950000,
      cashFlowSDE: 220000,
      netIncome: 180000,
      monthlyRent: 12000,
      yearEstablished: 2016,
      numberOfEmployees: 15,
      employeesWillingToStay: true,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 30,
      squareFootage: 3000,
      leaseTerms: "5 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Partner buyout",
      ffeValue: 200000,
      ffeIncluded: true,
      address: "220 W 23rd St, New York, NY 10011",
      neighborhood: "Chelsea",
      borough: "MANHATTAN" as const,
      zipCode: "10011",
      latitude: 40.7446,
      longitude: -73.9978,
      listedById: seller2.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "bay-ridge-auto-repair",
      title: "Bay Ridge Auto Repair Shop",
      description:
        "Established auto repair shop in Bay Ridge with a strong reputation and loyal customer base. 4 service bays, full alignment rack, and diagnostic equipment. ASE-certified mechanics on staff. Strong online reviews (4.7 stars on Google with 200+ reviews). Well-maintained equipment and clean facility.",
      category: "Auto Repair & Body Shops",
      askingPrice: 420000,
      annualRevenue: 780000,
      cashFlowSDE: 175000,
      monthlyRent: 5000,
      yearEstablished: 2010,
      numberOfEmployees: 5,
      employeesWillingToStay: true,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 45,
      squareFootage: 3500,
      leaseTerms: "9 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Retirement",
      trainingSupport: "60 days of training included",
      address: "7305 5th Ave, Brooklyn, NY 11209",
      neighborhood: "Bay Ridge",
      borough: "BROOKLYN" as const,
      zipCode: "11209",
      latitude: 40.6349,
      longitude: -74.0241,
      listedById: broker2.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "harlem-daycare-center",
      title: "Harlem Daycare & Learning Center",
      description:
        "Licensed daycare center in Harlem serving children ages 2-5. Capacity for 50 children, currently operating at 85% enrollment. Fully licensed with NYC DOHMH. Experienced staff with low turnover. Subsidized voucher program participation provides stable income. Recently upgraded facility with secure outdoor play area.",
      category: "Daycare & Childcare",
      askingPrice: 550000,
      annualRevenue: 820000,
      cashFlowSDE: 195000,
      monthlyRent: 6000,
      yearEstablished: 2013,
      numberOfEmployees: 12,
      employeesWillingToStay: true,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 40,
      squareFootage: 3200,
      leaseTerms: "7 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Relocating",
      licensesPermits: "NYC DOHMH Group Child Care License",
      address: "2345 Adam Clayton Powell Jr Blvd, New York, NY 10030",
      neighborhood: "Harlem",
      borough: "MANHATTAN" as const,
      zipCode: "10030",
      latitude: 40.8177,
      longitude: -73.9424,
      listedById: seller1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "flushing-bakery",
      title: "Flushing Asian Bakery",
      description:
        "Popular Asian bakery in downtown Flushing with high foot traffic location. Known for specialty breads, cakes, and pastries. Strong wholesale accounts with local restaurants. Modern commercial kitchen with bread oven, proof boxes, and display cases. Well-trained staff. Recipes included in sale.",
      category: "Bakeries",
      askingPrice: 320000,
      annualRevenue: 580000,
      cashFlowSDE: 140000,
      monthlyRent: 5800,
      yearEstablished: 2014,
      numberOfEmployees: 8,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 50,
      squareFootage: 1600,
      leaseTerms: "6 years remaining",
      reasonForSelling: "Family obligations",
      address: "135-20 Roosevelt Ave, Flushing, NY 11354",
      neighborhood: "Flushing",
      borough: "QUEENS" as const,
      zipCode: "11354",
      latitude: 40.7596,
      longitude: -73.8303,
      listedById: broker2.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "tribeca-bar-lounge",
      title: "Tribeca Cocktail Bar & Lounge",
      description:
        "Upscale cocktail bar and lounge in Tribeca with a sophisticated clientele. Stylish interior designed by a noted NYC designer. Full liquor license (SLA). Craft cocktail program with seasonal menus. Private event space available. Strong weekend revenue with growing weeknight business.",
      category: "Bars & Nightclubs",
      askingPrice: 900000,
      annualRevenue: 1400000,
      cashFlowSDE: 280000,
      netIncome: 220000,
      monthlyRent: 15000,
      yearEstablished: 2016,
      numberOfEmployees: 14,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 35,
      squareFootage: 2800,
      leaseTerms: "8 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Partnership dissolution",
      licensesPermits: "NYS Liquor Authority License",
      ffeValue: 250000,
      ffeIncluded: true,
      address: "74 Leonard St, New York, NY 10013",
      neighborhood: "Tribeca",
      borough: "MANHATTAN" as const,
      zipCode: "10013",
      latitude: 40.7174,
      longitude: -74.0055,
      listedById: broker1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "staten-island-convenience",
      title: "St. George Convenience Store",
      description:
        "Well-stocked convenience store near the Staten Island Ferry terminal. High foot traffic from commuters. Offers snacks, beverages, lottery, tobacco, and basic grocery items. Long operating hours with potential for extended services. Stable revenue with low overhead.",
      category: "Convenience Stores",
      askingPrice: 180000,
      annualRevenue: 420000,
      cashFlowSDE: 90000,
      monthlyRent: 3200,
      yearEstablished: 2017,
      numberOfEmployees: 3,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 60,
      squareFootage: 800,
      leaseTerms: "4 years remaining",
      reasonForSelling: "Moving out of city",
      inventoryValue: 25000,
      inventoryIncluded: true,
      address: "55 Bay St, Staten Island, NY 10301",
      neighborhood: "St. George",
      borough: "STATEN_ISLAND" as const,
      zipCode: "10301",
      latitude: 40.6433,
      longitude: -74.0773,
      listedById: seller2.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "east-village-pet-grooming",
      title: "East Village Pet Grooming & Spa",
      description:
        "Charming pet grooming and spa business in the East Village. Loyal customer base of dog and cat owners. Full grooming services plus retail sales of premium pet products. Strong online reviews and word-of-mouth referrals. Modern equipment and welcoming interior. Includes booking software and customer database.",
      category: "Pet Services",
      askingPrice: 220000,
      annualRevenue: 340000,
      cashFlowSDE: 100000,
      monthlyRent: 4500,
      yearEstablished: 2018,
      numberOfEmployees: 4,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 35,
      squareFootage: 900,
      leaseTerms: "5 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Pursuing other interests",
      address: "312 E 9th St, New York, NY 10003",
      neighborhood: "East Village",
      borough: "MANHATTAN" as const,
      zipCode: "10003",
      latitude: 40.7291,
      longitude: -73.9884,
      listedById: seller1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "sunset-park-cleaning-service",
      title: "Sunset Park Commercial Cleaning",
      description:
        "Established commercial cleaning service operating throughout Brooklyn and Manhattan. 20+ recurring commercial contracts including offices, retail stores, and medical facilities. Fleet of 3 company vehicles included. Trained crews with low turnover. All equipment and supplies included. Growth potential with residential services.",
      category: "Cleaning Services",
      askingPrice: 380000,
      annualRevenue: 720000,
      cashFlowSDE: 165000,
      netIncome: 135000,
      yearEstablished: 2011,
      numberOfEmployees: 18,
      employeesWillingToStay: true,
      ownerInvolvement: "ABSENTEE" as const,
      ownerHoursPerWeek: 15,
      reasonForSelling: "Retirement",
      sellerFinancing: true,
      trainingSupport: "90 days of training and client introductions",
      address: "4520 8th Ave, Brooklyn, NY 11220",
      neighborhood: "Sunset Park",
      borough: "BROOKLYN" as const,
      zipCode: "11220",
      latitude: 40.6453,
      longitude: -74.0004,
      listedById: broker2.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "lic-marketing-agency",
      title: "Long Island City Digital Marketing Agency",
      description:
        "Boutique digital marketing agency based in Long Island City serving small and mid-size businesses. Services include social media management, PPC advertising, SEO, and web design. Recurring monthly retainer model with 15+ active clients. Remote-capable team. Strong portfolio and case studies.",
      category: "Marketing & Advertising Agencies",
      askingPrice: 480000,
      annualRevenue: 650000,
      cashFlowSDE: 210000,
      netIncome: 175000,
      yearEstablished: 2015,
      numberOfEmployees: 6,
      employeesWillingToStay: true,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 30,
      squareFootage: 1200,
      leaseTerms: "3 years remaining",
      reasonForSelling: "Starting a new venture",
      sbaFinancingAvailable: true,
      address: "27-01 Queens Plaza N, Long Island City, NY 11101",
      neighborhood: "Long Island City",
      borough: "QUEENS" as const,
      zipCode: "11101",
      latitude: 40.7505,
      longitude: -73.9378,
      listedById: seller2.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "morris-park-pharmacy",
      title: "Morris Park Family Pharmacy",
      description:
        "Independent neighborhood pharmacy serving the Morris Park community. Full prescription services with strong insurance billing. OTC products, medical supplies, and health consultations. Loyal customer base with many multi-generational families. Modern POS and pharmacy management system.",
      category: "Pharmacies",
      askingPrice: 620000,
      annualRevenue: 1500000,
      cashFlowSDE: 250000,
      monthlyRent: 5500,
      yearEstablished: 2002,
      numberOfEmployees: 7,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 45,
      squareFootage: 1800,
      leaseTerms: "10 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Retirement",
      licensesPermits: "NYS Pharmacy License, DEA Registration",
      address: "1735 Williamsbridge Rd, Bronx, NY 10461",
      neighborhood: "Morris Park",
      borough: "BRONX" as const,
      zipCode: "10461",
      latitude: 40.8484,
      longitude: -73.8477,
      listedById: broker2.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "greenpoint-printing-shop",
      title: "Greenpoint Print & Copy Shop",
      description:
        "Full-service printing and copy shop in Greenpoint serving local businesses and residents. Services include digital and offset printing, large format, binding, and shipping. Commercial accounts provide stable B2B revenue. All equipment in good working order. Well-trained staff can run operations independently.",
      category: "Printing & Copy Shops",
      askingPrice: 195000,
      annualRevenue: 310000,
      cashFlowSDE: 85000,
      monthlyRent: 3800,
      yearEstablished: 2013,
      numberOfEmployees: 3,
      ownerInvolvement: "ABSENTEE" as const,
      ownerHoursPerWeek: 10,
      squareFootage: 1100,
      leaseTerms: "4 years remaining",
      reasonForSelling: "Focusing on other businesses",
      ffeValue: 80000,
      ffeIncluded: true,
      address: "138 Greenpoint Ave, Brooklyn, NY 11222",
      neighborhood: "Greenpoint",
      borough: "BROOKLYN" as const,
      zipCode: "11222",
      latitude: 40.7305,
      longitude: -73.9547,
      listedById: seller1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "uws-tutoring-center",
      title: "Upper West Side Tutoring Center",
      description:
        "Established tutoring and test prep center on the Upper West Side serving students K-12. SAT, ACT, SHSAT, and subject tutoring. Team of 20+ part-time tutors. Proprietary curriculum and materials. Online and in-person offerings. Strong referral network with local schools. Consistent enrollment with waitlist during peak seasons.",
      category: "Tutoring & Education Centers",
      askingPrice: 400000,
      annualRevenue: 580000,
      cashFlowSDE: 185000,
      monthlyRent: 6000,
      yearEstablished: 2011,
      numberOfEmployees: 4,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 25,
      squareFootage: 1400,
      leaseTerms: "6 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Relocating to another state",
      trainingSupport: "Full curriculum and operations manual included",
      address: "2478 Broadway, New York, NY 10025",
      neighborhood: "Upper West Side",
      borough: "MANHATTAN" as const,
      zipCode: "10025",
      latitude: 40.7924,
      longitude: -73.9728,
      listedById: broker1.id,
      status: "ACTIVE" as const,
    },
    {
      slug: "bensonhurst-liquor-store",
      title: "Bensonhurst Wine & Liquor",
      description:
        "Profitable wine and liquor store in a busy Bensonhurst shopping area. Well-curated selection of wines, spirits, and craft beers. Strong regular customer base. Modern POS system with inventory management. Recently renovated with new shelving and lighting. Delivery service adds additional revenue stream.",
      category: "Liquor Stores",
      askingPrice: 290000,
      annualRevenue: 650000,
      cashFlowSDE: 125000,
      monthlyRent: 4000,
      yearEstablished: 2016,
      numberOfEmployees: 3,
      ownerInvolvement: "OWNER_OPERATED" as const,
      ownerHoursPerWeek: 45,
      squareFootage: 1200,
      leaseTerms: "7 years remaining",
      leaseRenewalOption: true,
      reasonForSelling: "Personal reasons",
      licensesPermits: "NYS Liquor Authority License",
      inventoryValue: 65000,
      inventoryIncluded: true,
      address: "7218 18th Ave, Brooklyn, NY 11204",
      neighborhood: "Bensonhurst",
      borough: "BROOKLYN" as const,
      zipCode: "11204",
      latitude: 40.6144,
      longitude: -73.9868,
      listedById: seller2.id,
      status: "ACTIVE" as const,
    },
  ];

  for (const listing of listings) {
    await prisma.businessListing.upsert({
      where: { slug: listing.slug },
      update: {},
      create: listing,
    });
  }

  console.log(`Created ${listings.length} listings.`);
  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
