export const BUSINESS_CATEGORIES = [
  "Restaurants",
  "Bars & Nightclubs",
  "Cafes & Coffee Shops",
  "Bakeries",
  "Delis & Grocery Stores",
  "Food Trucks & Carts",
  "Retail Stores",
  "Clothing & Fashion",
  "Electronics",
  "Convenience Stores",
  "Pharmacies",
  "Laundromats & Dry Cleaners",
  "Salons & Barbershops",
  "Spas & Wellness",
  "Nail Salons",
  "Gyms & Fitness Studios",
  "Daycare & Childcare",
  "Auto Repair & Body Shops",
  "Gas Stations",
  "Car Washes",
  "Printing & Copy Shops",
  "Cleaning Services",
  "Construction & Contracting",
  "Real Estate Agencies",
  "Insurance Agencies",
  "Accounting & Tax Services",
  "Law Practices",
  "Medical & Dental Practices",
  "Home Health Agencies",
  "Trucking & Logistics",
  "Wholesale & Distribution",
  "Manufacturing",
  "E-commerce Businesses",
  "Tech & Software",
  "Marketing & Advertising Agencies",
  "Tutoring & Education Centers",
  "Pet Services",
  "Travel Agencies",
  "Event Planning",
  "Florists",
  "Liquor Stores",
  "Smoke Shops & Vape Shops",
  "Franchise Businesses",
  "Other",
] as const;

export type BusinessCategory = (typeof BUSINESS_CATEGORIES)[number];

export const BOROUGHS = [
  { value: "MANHATTAN", label: "Manhattan" },
  { value: "BROOKLYN", label: "Brooklyn" },
  { value: "QUEENS", label: "Queens" },
  { value: "BRONX", label: "Bronx" },
  { value: "STATEN_ISLAND", label: "Staten Island" },
] as const;

export type BoroughValue = (typeof BOROUGHS)[number]["value"];

export const NEIGHBORHOODS: Record<string, string[]> = {
  MANHATTAN: [
    "Upper East Side",
    "Upper West Side",
    "Midtown",
    "Midtown East",
    "Midtown West",
    "Chelsea",
    "Greenwich Village",
    "East Village",
    "West Village",
    "SoHo",
    "Tribeca",
    "Lower East Side",
    "Chinatown",
    "Little Italy",
    "Financial District",
    "NoHo",
    "NoLiTa",
    "Hell's Kitchen",
    "Murray Hill",
    "Gramercy",
    "Flatiron",
    "Kips Bay",
    "Harlem",
    "East Harlem",
    "Washington Heights",
    "Inwood",
    "Morningside Heights",
  ],
  BROOKLYN: [
    "Williamsburg",
    "Bushwick",
    "Park Slope",
    "Brooklyn Heights",
    "DUMBO",
    "Bed-Stuy",
    "Crown Heights",
    "Sunset Park",
    "Bay Ridge",
    "Flatbush",
    "Bensonhurst",
    "Greenpoint",
    "Cobble Hill",
    "Carroll Gardens",
    "Red Hook",
    "Borough Park",
    "Brighton Beach",
    "Coney Island",
    "Prospect Heights",
    "Fort Greene",
    "Clinton Hill",
    "Dyker Heights",
    "Midwood",
    "Sheepshead Bay",
    "Canarsie",
  ],
  QUEENS: [
    "Astoria",
    "Long Island City",
    "Flushing",
    "Jackson Heights",
    "Forest Hills",
    "Rego Park",
    "Jamaica",
    "Elmhurst",
    "Corona",
    "Woodside",
    "Sunnyside",
    "Bayside",
    "Fresh Meadows",
    "Ridgewood",
    "Howard Beach",
    "Ozone Park",
    "Richmond Hill",
    "Kew Gardens",
    "Maspeth",
    "Middle Village",
    "Whitestone",
    "College Point",
    "Far Rockaway",
  ],
  BRONX: [
    "South Bronx",
    "Mott Haven",
    "Fordham",
    "Riverdale",
    "Pelham Bay",
    "Throgs Neck",
    "Morris Park",
    "Belmont",
    "Kingsbridge",
    "Parkchester",
    "Hunts Point",
    "Tremont",
    "University Heights",
    "Norwood",
    "Wakefield",
    "Co-op City",
    "Castle Hill",
    "Soundview",
    "Westchester Square",
  ],
  STATEN_ISLAND: [
    "St. George",
    "Stapleton",
    "Tompkinsville",
    "New Dorp",
    "Tottenville",
    "Great Kills",
    "Eltingville",
    "Annadale",
    "Huguenot",
    "Charleston",
    "Travis",
    "Mariners Harbor",
    "Port Richmond",
    "West Brighton",
  ],
};

export const ALL_NEIGHBORHOODS = Object.values(NEIGHBORHOODS).flat();

export const LISTING_STATUSES = [
  { value: "ACTIVE", label: "Active" },
  { value: "UNDER_CONTRACT", label: "Under Contract" },
  { value: "SOLD", label: "Sold" },
  { value: "OFF_MARKET", label: "Off Market" },
] as const;

export const RELATED_CATEGORIES: Record<string, string[]> = {
  Restaurants: ["Bars & Nightclubs", "Cafes & Coffee Shops", "Bakeries", "Food Trucks & Carts"],
  "Bars & Nightclubs": ["Restaurants", "Liquor Stores", "Event Planning"],
  "Cafes & Coffee Shops": ["Restaurants", "Bakeries", "Delis & Grocery Stores"],
  Bakeries: ["Cafes & Coffee Shops", "Restaurants", "Delis & Grocery Stores"],
  "Delis & Grocery Stores": ["Convenience Stores", "Bakeries", "Liquor Stores"],
  "Food Trucks & Carts": ["Restaurants", "Cafes & Coffee Shops"],
  "Retail Stores": ["Clothing & Fashion", "Electronics", "Convenience Stores"],
  "Clothing & Fashion": ["Retail Stores", "E-commerce Businesses"],
  Electronics: ["Retail Stores", "E-commerce Businesses", "Tech & Software"],
  "Convenience Stores": ["Delis & Grocery Stores", "Retail Stores", "Smoke Shops & Vape Shops"],
  Pharmacies: ["Medical & Dental Practices", "Home Health Agencies"],
  "Laundromats & Dry Cleaners": ["Cleaning Services", "Salons & Barbershops"],
  "Salons & Barbershops": ["Nail Salons", "Spas & Wellness"],
  "Spas & Wellness": ["Salons & Barbershops", "Nail Salons", "Gyms & Fitness Studios"],
  "Nail Salons": ["Salons & Barbershops", "Spas & Wellness"],
  "Gyms & Fitness Studios": ["Spas & Wellness", "Daycare & Childcare"],
  "Daycare & Childcare": ["Tutoring & Education Centers"],
  "Auto Repair & Body Shops": ["Gas Stations", "Car Washes"],
  "Gas Stations": ["Auto Repair & Body Shops", "Car Washes", "Convenience Stores"],
  "Car Washes": ["Auto Repair & Body Shops", "Gas Stations"],
  "Liquor Stores": ["Bars & Nightclubs", "Delis & Grocery Stores", "Convenience Stores"],
  "Smoke Shops & Vape Shops": ["Convenience Stores", "Retail Stores"],
  "E-commerce Businesses": ["Tech & Software", "Retail Stores", "Marketing & Advertising Agencies"],
  "Tech & Software": ["E-commerce Businesses", "Marketing & Advertising Agencies"],
};

export const PRICE_RANGES = [
  { label: "Under $50K", min: 0, max: 50000 },
  { label: "$50K - $100K", min: 50000, max: 100000 },
  { label: "$100K - $250K", min: 100000, max: 250000 },
  { label: "$250K - $500K", min: 250000, max: 500000 },
  { label: "$500K - $1M", min: 500000, max: 1000000 },
  { label: "$1M - $2.5M", min: 1000000, max: 2500000 },
  { label: "$2.5M - $5M", min: 2500000, max: 5000000 },
  { label: "$5M+", min: 5000000, max: null },
] as const;
